apiVersion: v1
kind: Pod
metadata:
  name: sample-entrypoint
  labels:
    app.kubernetes.io/name: sample-entrypoint
spec:
  containers:
    - name: nginx-container-112
      image: nginx:1.16
      command: ["/bin/sleep"] # Docker의 ENTRYPOINT와 동일
      args: ["3600"] # Docker의 CMD와 동일
