apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-ttl
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  ttlSecondsAfterFinished: 30 # 종료 후 일정 시간 경과 후 삭제되도록 설정
  template:
    spec:
      containers:
        - name: tools-container
          image: amsy810/tools:v2.0
          command: ["sleep"]
          args: ["60"]
      restartPolicy: Never
