apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-tools
  template:
    metadata:
      labels:
        app: centos-tools
    spec:
      containers:
        - name: centos-tools
          image: centos/tools:no # 잘못된 버전
          command: ["/bin/bash", "-c", "sleep infinity"]
