apiVersion: v1
kind: Service
metadata:
  name: sample-none-selector
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: sample-none-selector
  labels:
    kubernetes.io/service-name: sample-none-selector
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.1.1"
      - "192.168.1.2"
ports:
  - protocol: TCP
    port: 80
