apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: test

--- # 한개의 yaml 파일에 복수의 리소스를 정의할 때는 --- 로 구분
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: docker.io/library/busybox
      command: ["env"]
      envFrom:
        - configMapRef:
            name: test-config
