apiVersion: v1
kind: Pod
metadata:
  name: sample-hostnetwork
  labels:
    app.kubernetes.io/name: sample-hostnetwork
spec:
  hostNetwork: true
  containers:
    - name: nginx-container
      image: nginx:1.16
