apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
spec:
  description: "Test AppProject"
  sourceRepos:
    - https://github.com/kyumin1227/fastapi-sample.git
  destinations:
    - namespace: test
      server: https://kubernetes.default.svc
