apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx # 레플리카셋의 라벨
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx # 레플리카셋이 관리할 라벨 셀렉터
  template:
    metadata:
      labels:
        app: nginx # pod의 라벨로 레플리카셋이 관리할 라벨 셀렉터와 매칭되어야 함
    spec:
      containers:
        - name: nginx
          image: nginx
